### ISSUE TITLE
Trash icon for simulations

### ISSUE THREAD

**Issue by stefaniapedrazzi** [cyberbotics/webots-cloud#59]
When a user is logged it, the trash icon for animation loaded by the user itself is blue and all the others are red.
But for simulations there is not this difference and all the trash are red.

I don't know if there is a reason for this.
But it is very useful to have anything that identifies which are the scenes/animations/simulations loaded by the current users, given that there is not even a user column in the table.

Maybe a future feature could to add a filter to show only the own scenes/animations/simulations/servers.

**Comment by BenjaminDeleze** [comment]
You see the red icon because your are an administrator.

The trash icon follows this code:
- blue: you own the animation/scene => only you can delete it.
- white: nobody own the animation/scene => everybody can remove it.
- red: animation/scene owned by someone else. Normal user do not see red trash icon, if the animation/scene belongs to someone else, there is no thrash icon for them. The red icon means that, as an admin, you can remove the animation/scene owned by someone else.

Special case for simulations:
Simulation are not owned (it is just a link to a repo), so the normal way to remove one is to change the `.yaml` file in the github repo (which you can do only if you are the user.
However, as an admin, you can remove the simulation directly on the webots.cloud.

I agree that the filter to see only its animation/scene is a good idea.

**Comment by omichel** [comment]
> I agree that the filter to see only its animation/scene is a good idea.

Adding a "mine" check-box next to the search box could be a solution.
